name: 构建

on:
  push:
    branches: [ 'main' ]
    paths: [ 'version.txt', '.github/workflows/build.yml' ]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 获取版本号
        run: |
          versions=$(head -n 1 version.txt)
          tagList=""
          IFS=',' read -ra versionList <<< "$versions"
          cuVersion="${versionList[0]}"
          for version in "${versionList[@]}"; do
            tagList+="dr34m/pyinstaller:$version,"
          done
          tagList=${tagList%?}
          echo "tagList=$tagList" >> $GITHUB_ENV

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: 设置Docker BuildX
        uses: docker/setup-buildx-action@v3
    
      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: dr34m
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送A类型
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.a
          push: true
          tags: ${{ env.tagList }}
          platforms: linux/amd64,linux/arm64

      - name: 构建并推送B类型
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.b
          push: true
          tags: ${{ env.tagList }}
          platforms: linux/arm/v7,linux/386,linux/arm/v6,linux/s390x,linux/ppc64le
    