name: 构建

on:
  push:
    branches: [ 'main' ]
    paths: [ 'Dockerfile.taosync', '.github/workflows/buildTaoSync.yml' ]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: 设置Docker BuildX
        uses: docker/setup-buildx-action@v3
    
      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: dr34m
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.taosync
          push: true
          tags: dr34m/pyinstaller:taosync
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x,linux/ppc64le
